//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMedia")]
public interface IMedia
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveMedia", ReplyAction="http://tempuri.org/IMedia/SaveMediaResponse")]
    void SaveMedia(string path, string events, string persons, string peisaj, string locatie, string altele, System.DateTime creationDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveMedia", ReplyAction="http://tempuri.org/IMedia/SaveMediaResponse")]
    System.Threading.Tasks.Task SaveMediaAsync(string path, string events, string persons, string peisaj, string locatie, string altele, System.DateTime creationDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/DeleteMedia", ReplyAction="http://tempuri.org/IMedia/DeleteMediaResponse")]
    void DeleteMedia(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/DeleteMedia", ReplyAction="http://tempuri.org/IMedia/DeleteMediaResponse")]
    System.Threading.Tasks.Task DeleteMediaAsync(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowGridData", ReplyAction="http://tempuri.org/IMedia/ShowGridDataResponse")]
    object ShowGridData();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowGridData", ReplyAction="http://tempuri.org/IMedia/ShowGridDataResponse")]
    System.Threading.Tasks.Task<object> ShowGridDataAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowData", ReplyAction="http://tempuri.org/IMedia/ShowDataResponse")]
    object ShowData();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowData", ReplyAction="http://tempuri.org/IMedia/ShowDataResponse")]
    System.Threading.Tasks.Task<object> ShowDataAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveFile", ReplyAction="http://tempuri.org/IMedia/SaveFileResponse")]
    string SaveFile();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveFile", ReplyAction="http://tempuri.org/IMedia/SaveFileResponse")]
    System.Threading.Tasks.Task<string> SaveFileAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/EditData", ReplyAction="http://tempuri.org/IMedia/EditDataResponse")]
    void EditData(string pathForEdit, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/EditData", ReplyAction="http://tempuri.org/IMedia/EditDataResponse")]
    System.Threading.Tasks.Task EditDataAsync(string pathForEdit, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/FindData", ReplyAction="http://tempuri.org/IMedia/FindDataResponse")]
    string FindData(string result, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/FindData", ReplyAction="http://tempuri.org/IMedia/FindDataResponse")]
    System.Threading.Tasks.Task<string> FindDataAsync(string result, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMediaChannel : IMedia, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MediaClient : System.ServiceModel.ClientBase<IMedia>, IMedia
{
    
    public MediaClient()
    {
    }
    
    public MediaClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MediaClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MediaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MediaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SaveMedia(string path, string events, string persons, string peisaj, string locatie, string altele, System.DateTime creationDate)
    {
        base.Channel.SaveMedia(path, events, persons, peisaj, locatie, altele, creationDate);
    }
    
    public System.Threading.Tasks.Task SaveMediaAsync(string path, string events, string persons, string peisaj, string locatie, string altele, System.DateTime creationDate)
    {
        return base.Channel.SaveMediaAsync(path, events, persons, peisaj, locatie, altele, creationDate);
    }
    
    public void DeleteMedia(string path)
    {
        base.Channel.DeleteMedia(path);
    }
    
    public System.Threading.Tasks.Task DeleteMediaAsync(string path)
    {
        return base.Channel.DeleteMediaAsync(path);
    }
    
    public object ShowGridData()
    {
        return base.Channel.ShowGridData();
    }
    
    public System.Threading.Tasks.Task<object> ShowGridDataAsync()
    {
        return base.Channel.ShowGridDataAsync();
    }
    
    public object ShowData()
    {
        return base.Channel.ShowData();
    }
    
    public System.Threading.Tasks.Task<object> ShowDataAsync()
    {
        return base.Channel.ShowDataAsync();
    }
    
    public string SaveFile()
    {
        return base.Channel.SaveFile();
    }
    
    public System.Threading.Tasks.Task<string> SaveFileAsync()
    {
        return base.Channel.SaveFileAsync();
    }
    
    public void EditData(string pathForEdit, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele)
    {
        base.Channel.EditData(pathForEdit, editEvent, editPerson, editPeisaj, editLoc, editAltele);
    }
    
    public System.Threading.Tasks.Task EditDataAsync(string pathForEdit, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele)
    {
        return base.Channel.EditDataAsync(pathForEdit, editEvent, editPerson, editPeisaj, editLoc, editAltele);
    }
    
    public string FindData(string result, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele)
    {
        return base.Channel.FindData(result, editEvent, editPerson, editPeisaj, editLoc, editAltele);
    }
    
    public System.Threading.Tasks.Task<string> FindDataAsync(string result, string editEvent, string editPerson, string editPeisaj, string editLoc, string editAltele)
    {
        return base.Channel.FindDataAsync(result, editEvent, editPerson, editPeisaj, editLoc, editAltele);
    }
}
