//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAndApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public int Moved { get; set; }
        public string Evenimente { get; set; }
        public string Persoane { get; set; }
        public string Peisaje { get; set; }
        public string Locuri { get; set; }
        public string Altele { get; set; }
        public string DataCreare { get; set; }
    }
}
