//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMedia")]
public interface IMedia
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveMedia", ReplyAction="http://tempuri.org/IMedia/SaveMediaResponse")]
    object SaveMedia(string sqlCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveMedia", ReplyAction="http://tempuri.org/IMedia/SaveMediaResponse")]
    System.Threading.Tasks.Task<object> SaveMediaAsync(string sqlCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/DeleteMedia", ReplyAction="http://tempuri.org/IMedia/DeleteMediaResponse")]
    object DeleteMedia(string sqlCommand, string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/DeleteMedia", ReplyAction="http://tempuri.org/IMedia/DeleteMediaResponse")]
    System.Threading.Tasks.Task<object> DeleteMediaAsync(string sqlCommand, string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowGridData", ReplyAction="http://tempuri.org/IMedia/ShowGridDataResponse")]
    object ShowGridData(string sqlCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowGridData", ReplyAction="http://tempuri.org/IMedia/ShowGridDataResponse")]
    System.Threading.Tasks.Task<object> ShowGridDataAsync(string sqlCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowData", ReplyAction="http://tempuri.org/IMedia/ShowDataResponse")]
    object ShowData(string sqlCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/ShowData", ReplyAction="http://tempuri.org/IMedia/ShowDataResponse")]
    System.Threading.Tasks.Task<object> ShowDataAsync(string sqlCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveFile", ReplyAction="http://tempuri.org/IMedia/SaveFileResponse")]
    object SaveFile(string sqlCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/SaveFile", ReplyAction="http://tempuri.org/IMedia/SaveFileResponse")]
    System.Threading.Tasks.Task<object> SaveFileAsync(string sqlCommand);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMediaChannel : IMedia, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MediaClient : System.ServiceModel.ClientBase<IMedia>, IMedia
{
    
    public MediaClient()
    {
    }
    
    public MediaClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MediaClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MediaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MediaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public object SaveMedia(string sqlCommand)
    {
        return base.Channel.SaveMedia(sqlCommand);
    }
    
    public System.Threading.Tasks.Task<object> SaveMediaAsync(string sqlCommand)
    {
        return base.Channel.SaveMediaAsync(sqlCommand);
    }
    
    public object DeleteMedia(string sqlCommand, string path)
    {
        return base.Channel.DeleteMedia(sqlCommand, path);
    }
    
    public System.Threading.Tasks.Task<object> DeleteMediaAsync(string sqlCommand, string path)
    {
        return base.Channel.DeleteMediaAsync(sqlCommand, path);
    }
    
    public object ShowGridData(string sqlCommand)
    {
        return base.Channel.ShowGridData(sqlCommand);
    }
    
    public System.Threading.Tasks.Task<object> ShowGridDataAsync(string sqlCommand)
    {
        return base.Channel.ShowGridDataAsync(sqlCommand);
    }
    
    public object ShowData(string sqlCommand)
    {
        return base.Channel.ShowData(sqlCommand);
    }
    
    public System.Threading.Tasks.Task<object> ShowDataAsync(string sqlCommand)
    {
        return base.Channel.ShowDataAsync(sqlCommand);
    }
    
    public object SaveFile(string sqlCommand)
    {
        return base.Channel.SaveFile(sqlCommand);
    }
    
    public System.Threading.Tasks.Task<object> SaveFileAsync(string sqlCommand)
    {
        return base.Channel.SaveFileAsync(sqlCommand);
    }
}
